package tasks

import groovy.json.JsonSlurper
import java.io.File

/**
 * Shared logic that turns `formats/formats.json` into the generated format registry source.
 * Used by [GenerateFormatRegistry] and by the verification tasks so generation
 * and verification can never drift apart.
 */
internal object FormatRegistryGenerator {
  private val FORMAT_NAME_PATTERN = Regex("[a-z0-9]+(-[a-z0-9]+)*")
  private val VALIDATOR_NAME_PATTERN = Regex("[A-Z][A-Za-z0-9]*FormatValidator")

  internal data class FormatSpec(
    val name: String,
    val validator: String,
  )

  fun parse(specFile: File): List<FormatSpec> {
    require(specFile.isFile) { "format spec file $specFile does not exist" }
    val parsed: Any? = JsonSlurper().parse(specFile)
    require(parsed is Map<*, *>) { "format spec $specFile must contain a JSON object" }
    val formats: Any? = parsed["formats"]
    require(formats is List<*>) { "format spec $specFile must contain a 'formats' array" }
    return formats.mapIndexed { index, entry ->
      require(entry is Map<*, *>) { "entry #$index in $specFile must be a JSON object" }
      val name: String? = entry["name"] as? String
      require(!name.isNullOrBlank()) { "entry #$index in $specFile does not define a string 'name'" }
      require(name.matches(FORMAT_NAME_PATTERN)) {
        "format name '$name' in $specFile must be lowercase kebab-case ($FORMAT_NAME_PATTERN)"
      }
      val validator: String? = entry["validator"] as? String
      require(!validator.isNullOrBlank()) { "entry #$index ('$name') in $specFile does not define a string 'validator'" }
      require(validator.matches(VALIDATOR_NAME_PATTERN)) {
        "validator '$validator' for format '$name' in $specFile must match $VALIDATOR_NAME_PATTERN"
      }
      FormatSpec(name, validator)
    }.sortedBy { it.name }.also { specs ->
      val duplicates: Set<String> = specs.groupBy { it.name }.filterValues { it.size > 1 }.keys
      require(duplicates.isEmpty()) { "duplicate format names in $specFile: ${duplicates.sorted()}" }
    }
  }

  fun generate(formats: List<FormatSpec>): String =
    buildString {
      appendLine("// Generated by the generateFormatRegistry Gradle task from formats/formats.json.")
      appendLine("// Do not edit manually. Run ./gradlew :json-schema-validator:generateFormatRegistry to update.")
      appendLine("package io.github.optimumcode.json.schema.internal.formats")
      appendLine()
      appendLine("import io.github.optimumcode.json.schema.FormatValidator")
      appendLine()
      appendLine("internal object GeneratedFormatRegistry {")
      appendLine("  val formatNames: Set<String> =")
      appendLine("    setOf(")
      formats.forEach { appendLine("      \"${it.name}\",") }
      appendLine("    )")
      appendLine()
      appendLine("  val knownFormats: Map<String, FormatValidator> =")
      appendLine("    mapOf(")
      formats.forEach { appendLine("      \"${it.name}\" to ${it.validator},") }
      appendLine("    )")
      append("}")
    }
}