package tasks

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Generates Kotlin sources from the gate fixture JSON files.
 *
 * Fixtures are plain JSON checked in under the module's `src` tree:
 * - `commonFixtures` become a source file in the `commonTest` source set
 *   and must be collected by every target.
 * - `targetFixtures/<family>` become source files for one target family
 *   (`jvm`, `js`, `wasmJs`, `native`) and are reported as target-specific.
 *
 * Generation is fully deterministic (sorted file names, embedded raw JSON)
 * so the output only changes when a fixture file is added, removed or edited.
 */
abstract class GenerateGateFixtures : DefaultTask() {
  @get:InputDirectory
  abstract val commonFixturesDir: DirectoryProperty

  @get:InputDirectory
  abstract val targetFixturesDir: DirectoryProperty

  @get:OutputDirectory
  abstract val outputDir: DirectoryProperty

  init {
    group = "generation"
    description = "Generates Kotlin sources for the multiplatform collection gate fixtures"
  }

  @TaskAction
  protected fun generate() {
    val out = outputDir.get().asFile
    out.deleteRecursively()
    out.mkdirs()

    writeFixtureFile(
      packageSegment = "common",
      marker = "COMMON",
      fixtureDir = commonFixturesDir.get().asFile,
    )

    val targetRoot = targetFixturesDir.get().asFile
    val families =
      targetRoot.listFiles { file -> file.isDirectory }?.sortedBy { it.name }
        ?: throw GradleException("cannot list target fixture families under ${project.relativePath(targetRoot)}")
    for (familyDir in families) {
      require(familyDir.name in TARGET_FAMILIES) {
        "unknown target fixture family '${familyDir.name}', expected one of $TARGET_FAMILIES"
      }
      writeFixtureFile(
        packageSegment = familyDir.name.sanitizePackageSegment,
        marker = familyDir.name.uppercase().replace('-', '_'),
        fixtureDir = familyDir,
      )
    }
  }

  private fun writeFixtureFile(
    packageSegment: String,
    marker: String,
    fixtureDir: File,
  ) {
    val files =
      fixtureDir.listFiles { file -> file.isFile && file.extension == "json" }?.sortedBy { it.name }
        ?: throw GradleException("cannot list fixtures in ${project.relativePath(fixtureDir)}")
    require(files.isNotEmpty()) {
      "fixture directory ${project.relativePath(fixtureDir)} contains no JSON fixtures"
    }

    val entries =
      files.joinToString(separator = ",\n") { file ->
        val content = file.readText().trim()
        if (content.contains(TRIPLE_QUOTE)) {
          throw GradleException(
            "fixture ${project.relativePath(file)} must not contain a triple quote: embedding would break",
          )
        }
        buildString {
          append("    \"")
          append(file.nameWithoutExtension)
          append("\" to ")
          append(TRIPLE_QUOTE)
          append(content)
          append(TRIPLE_QUOTE)
        }
      }

    val source =
      """
      |$FILE_HEADER
      |package io.github.optimumcode.json.schema.gate.generated.$packageSegment
      |
      |internal val ${marker}_GATE_FIXTURES: Map<String, String> =
      |  mapOf(
      |$entries
      |  )
      |
      """.trimMargin()

    val suffix = if (packageSegment == "common") "common" else packageSegment
    val fileName = if (packageSegment == "common") "GeneratedCommonGateFixtures.kt" else "GeneratedGateFixtures.kt"
    val target = File(outputDir.get().asFile, "$suffix/$fileName")
    target.parentFile.mkdirs()
    target.writeText(source)
    logger.lifecycle("Generated {} gate fixtures into {}", marker, project.relativePath(target))
  }

  private companion object {
    const val FILE_HEADER = "// Generated by generateGateFixtures. DO NOT EDIT MANUALLY."
    const val TRIPLE_QUOTE = "\"\"\""
    val TARGET_FAMILIES = setOf("jvm", "js", "wasmJs", "native")

    /** Keeps generated package segments valid Kotlin identifiers. */
    val String.sanitizePackageSegment: String
      get() = replace('-', '_')
  }
}
