package tasks

import com.google.gson.JsonObject
import com.google.gson.JsonParser
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Generates the `KnownFormats.kt` registry from a declarative format spec (JSON).
 *
 * The generated file is checked into the repository. Use the corresponding
 * `syncKnownFormats` task to update the checked-in copy and `verifyKnownFormats`
 * to detect drift between the spec and the checked-in generated source.
 */
abstract class GenerateKnownFormats : DefaultTask() {
  @get:InputFile
  abstract val specFile: RegularFileProperty

  @get:Input
  abstract val packageName: Property<String>

  @get:OutputDirectory
  abstract val outputDir: DirectoryProperty

  init {
    group = "generation"
    description = "Generates the known-formats registry Kotlin source from the format spec"
  }

  @TaskAction
  fun generate() {
    val spec = parseSpec(specFile.get().asFile.readText(), specFile.get().asFile.path)
    val pkg = packageName.get()
    val targetDir = outputDir.get().asFile
    val packageDir = pkg.split('.').fold(targetDir, ::java.io.File)
    packageDir.mkdirs()
    val outputFile = packageDir.resolve("KnownFormats.kt")
    outputFile.writeText(renderKnownFormats(pkg, spec))
    logger.lifecycle("generated ${outputFile.relativeTo(project.rootDir)} from ${specFile.get().asFile.name}")
  }

  internal companion object {
    internal data class FormatEntry(
      val name: String,
      val validator: String,
    )

    internal fun parseSpec(
      content: String,
      location: String,
    ): List<FormatEntry> {
      val root =
        runCatching { JsonParser.parseString(content).asJsonObject }
          .getOrElse { throw GradleException("cannot parse format spec '$location': ${it.message}", it) }
      val formats =
        root.getAsJsonArray("formats")
          ?: throw GradleException("format spec '$location' does not contain a 'formats' array")
      val entries =
        formats.map { element ->
          val obj: JsonObject =
            if (element.isJsonObject) {
              element.asJsonObject
            } else {
              throw GradleException("format spec '$location' contains a non-object entry: $element")
            }
          val name =
            obj.get("name")?.takeIf { it.isJsonPrimitive }?.asString
              ?: throw GradleException("format spec entry in '$location' misses the 'name' property: $obj")
          val validator =
            obj.get("validator")?.takeIf { it.isJsonPrimitive }?.asString
              ?: throw GradleException("format spec entry '$name' in '$location' misses the 'validator' property")
          FormatEntry(name, validator)
        }
      val problems = mutableListOf<String>()
      entries.forEach { entry ->
        if (entry.name.isBlank() || entry.name != entry.name.lowercase()) {
          problems += "format name '${entry.name}' must be a non-blank lowercase string"
        }
        if (!entry.validator.matches(Regex("[A-Za-z][A-Za-z0-9]*"))) {
          problems += "validator '${entry.validator}' for format '${entry.name}' is not a valid class name"
        }
      }
      entries.groupingBy { it.name }.eachCount().filter { it.value > 1 }.keys.forEach {
        problems += "format '$it' is declared more than once"
      }
      if (entries.isEmpty()) {
        problems += "format spec must declare at least one format"
      }
      if (problems.isNotEmpty()) {
        throw GradleException(
          "invalid format spec '$location':\n" + problems.joinToString("\n") { "  - $it" },
        )
      }
      return entries.sortedBy { it.name }
    }

    internal fun renderKnownFormats(
      pkg: String,
      entries: List<FormatEntry>,
    ): String =
      buildString {
        appendLine("// Generated by the generateKnownFormats task. Do not edit manually.")
        appendLine("// Update the format spec and run the syncKnownFormats task to regenerate.")
        appendLine("package $pkg")
        appendLine()
        appendLine("import io.github.optimumcode.json.schema.FormatValidator")
        appendLine()
        appendLine("internal val KNOWN_FORMATS: Map<String, FormatValidator> =")
        appendLine("  mapOf(")
        entries.forEach { entry ->
          appendLine("    \"${entry.name}\" to ${entry.validator},")
        }
        appendLine("  )")
      }
  }
}
