package tasks

import groovy.json.JsonSlurper
import org.gradle.api.GradleException
import java.io.File

/**
 * Shared generation logic for the verification module.
 *
 * The generated sources are checked into the repository (same pattern as the binary-compatibility
 * API dumps). [tasks.GenerateVerificationSources] refreshes them and
 * [tasks.VerifyGeneratedSourcesDrift] fails the build when the checked-in content no longer
 * matches a fresh regeneration. The generation is deterministic (sorted entries, no timestamps,
 * no absolute paths) so a regeneration always leaves the working tree clean.
 */
internal object VerificationSourceGenerator {
  const val GENERATED_PACKAGE: String = "io.github.optimumcode.json.schema.verification"
  const val MANIFEST_FILE_NAME: String = "FixtureManifest.kt"
  const val EXPECTED_FORMATS_FILE_NAME: String = "ExpectedFormats.kt"

  private const val HEADER: String =
    "// AUTO-GENERATED by :verification:generateVerificationSources. Do not edit manually.\n" +
      "// Regenerate with: ./gradlew :verification:generateVerificationSources\n"

  private val FIXTURE_CATEGORIES: List<Pair<String, String>> =
    listOf(
      "common" to "common",
      "optional" to "optional",
      "format" to "optional/format",
    )

  fun generatedFiles(fixturesDir: File, formatRegistrySource: File): Map<String, String> =
    linkedMapOf(
      MANIFEST_FILE_NAME to generateFixtureManifest(fixturesDir),
      EXPECTED_FORMATS_FILE_NAME to generateExpectedFormats(formatRegistrySource),
    )

  private fun generateFixtureManifest(fixturesDir: File): String {
    val categories = linkedMapOf<String, CategoryStats>()
    for ((name, relativeDir) in FIXTURE_CATEGORIES) {
      categories[name] = collectCategory(File(fixturesDir, relativeDir), "category '$name'")
    }
    val targetSpecificDir = File(fixturesDir, "target-specific")
    if (!targetSpecificDir.isDirectory) {
      throw GradleException(
        "target-specific fixture directory does not exist: ${targetSpecificDir.path}. " +
          "The verification fixtures must define at least one target-specific family",
      )
    }
    val targetSpecific = linkedMapOf<String, CategoryStats>()
    targetSpecificDir.listFiles()
      ?.filter { it.isDirectory }
      ?.sortedBy { it.name }
      ?.forEach { familyDir ->
        targetSpecific[familyDir.name] =
          collectCategory(familyDir, "target-specific family '${familyDir.name}'")
      }
    if (targetSpecific.isEmpty()) {
      throw GradleException(
        "no target-specific fixture families found in ${targetSpecificDir.path}. " +
          "The verification fixtures must define at least one target-specific family",
      )
    }
    return renderManifest(categories, targetSpecific)
  }

  private data class CategoryStats(
    val suites: Int,
    val cases: Int,
    val suiteIds: List<String>,
  )

  private fun collectCategory(dir: File, description: String): CategoryStats {
    if (!dir.isDirectory) {
      throw GradleException("fixture $description directory does not exist: ${dir.path}")
    }
    val files =
      dir.listFiles()
        ?.filter { it.isFile && it.name.endsWith(".json") }
        ?.sortedBy { it.name }
        .orEmpty()
    var cases = 0
    val suiteIds =
      files.map { file ->
        val suites = JsonSlurper().parse(file, Charsets.UTF_8)
        if (suites !is List<*>) {
          throw GradleException("fixture file ${file.path} must contain a JSON array of test suites")
        }
        for (suite in suites) {
          if (suite !is Map<*, *>) {
            throw GradleException("fixture file ${file.path} contains a suite that is not a JSON object")
          }
          val tests = suite["tests"]
          if (tests !is List<*> || tests.isEmpty()) {
            throw GradleException(
              "fixture file ${file.path} contains suite '${suite["description"]}' without test cases",
            )
          }
          cases += tests.size
        }
        file.name.removeSuffix(".json")
      }
    if (cases == 0) {
      throw GradleException(
        "fixture $description collected 0 test cases from ${files.size} suite file(s) in ${dir.path}. " +
          "Zero collection is not allowed: either restore the fixtures or remove the category deliberately",
      )
    }
    return CategoryStats(suites = files.size, cases = cases, suiteIds = suiteIds)
  }

  private fun renderManifest(
    categories: Map<String, CategoryStats>,
    targetSpecific: Map<String, CategoryStats>,
  ): String =
    buildString {
      append(HEADER)
      append("package ").append(GENERATED_PACKAGE).append("\n\n")
      append("internal data class FixtureCategory(\n")
      append("  val suites: Int,\n")
      append("  val cases: Int,\n")
      append("  val suiteIds: List<String>,\n")
      append(")\n\n")
      append("internal object FixtureManifest {\n")
      append("  val categories: Map<String, FixtureCategory> =\n")
      append("    mapOf(\n")
      for ((name, stats) in categories) {
        append("      ").append(renderCategory(name, stats)).append(",\n")
      }
      append("    )\n\n")
      append("  val targetSpecific: Map<String, FixtureCategory> =\n")
      append("    mapOf(\n")
      for ((family, stats) in targetSpecific) {
        append("      ").append(renderCategory(family, stats)).append(",\n")
      }
      append("    )\n")
      append("}\n")
    }

  private fun renderCategory(name: String, stats: CategoryStats): String {
    val suiteIds = stats.suiteIds.joinToString(", ") { "\"$it\"" }
    return "\"$name\" to FixtureCategory(suites = ${stats.suites}, cases = ${stats.cases}, suiteIds = listOf($suiteIds))"
  }

  private val FORMAT_REGISTRY_ENTRY = Regex("\"([a-z0-9][a-z0-9-]*)\" to (\\w+FormatValidator)")

  private fun generateExpectedFormats(formatRegistrySource: File): String {
    if (!formatRegistrySource.isFile) {
      throw GradleException("format registry source does not exist: ${formatRegistrySource.path}")
    }
    val formatNames =
      FORMAT_REGISTRY_ENTRY.findAll(formatRegistrySource.readText())
        .map { it.groupValues[1] }
        .toSortedSet()
        .toList()
    if (formatNames.isEmpty()) {
      throw GradleException(
        "no format registry entries found in ${formatRegistrySource.path}. " +
          "The KNOWN_FORMATS registry could not be parsed",
      )
    }
    return buildString {
      append(HEADER)
      append("package ").append(GENERATED_PACKAGE).append("\n\n")
      append("internal object ExpectedFormats {\n")
      append("  val formatNames: List<String> =\n")
      append("    listOf(\n")
      for (name in formatNames) {
        append("      \"").append(name).append("\",\n")
      }
      append("    )\n")
      append("}\n")
    }
  }
}
