package io.github.optimumcode.json.schema.gates

import okio.FileSystem
import okio.Path
import java.security.MessageDigest

private const val GENERATED_PACKAGE: String = "io.github.optimumcode.json.schema.gates.generated"
private const val GENERATE_TASK: String = ":json-schema-validator-gates:generateSpecFixtureManifest"

/**
 * Generates the committed manifest source from the fixture files.
 * The output is deterministic: fixtures are sorted by id and no timestamps or
 * absolute paths are embedded, so regenerating after a real change is the only
 * way the content can differ.
 */
public class ManifestGenerator(
  private val fs: FileSystem,
) {
  private val collector = FixtureCollector(fs)

  public fun expectations(fixturesDir: Path): List<FixtureExpectation> =
    collector.collect(fixturesDir).map { fixture ->
      FixtureExpectation(
        id = fixture.id,
        sha256 = sha256(fs, fixturesDir / "suites" / "${fixture.id}.json"),
        suites = fixture.groups.size,
        tests = fixture.testCount,
      )
    }

  public fun revision(expectations: List<FixtureExpectation>): String {
    val digest = MessageDigest.getInstance("SHA-256")
    for (expectation in expectations.sortedBy(FixtureExpectation::id)) {
      digest.update("${expectation.id}:${expectation.sha256}\n".toByteArray(Charsets.UTF_8))
    }
    return digest.digest().toHex()
  }

  public fun generate(fixturesDir: Path): String {
    val expectations = expectations(fixturesDir)
    val revision = revision(expectations)
    return buildString {
      appendLine("// This file is generated by ./gradlew $GENERATE_TASK. Do not edit manually.")
      appendLine("@file:Suppress(\"ConstPropertyName\")")
      appendLine()
      appendLine("package $GENERATED_PACKAGE")
      appendLine()
      appendLine("import io.github.optimumcode.json.schema.gates.FixtureExpectation")
      appendLine()
      appendLine("public const val SPEC_FIXTURE_MANIFEST_REVISION: String = \"$revision\"")
      appendLine()
      appendLine("public val SPEC_FIXTURE_MANIFEST: List<FixtureExpectation> =")
      appendLine("  listOf(")
      for (expectation in expectations) {
        appendLine("    FixtureExpectation(")
        appendLine("      id = \"${expectation.id}\",")
        appendLine("      sha256 = \"${expectation.sha256}\",")
        appendLine("      suites = ${expectation.suites},")
        appendLine("      tests = ${expectation.tests},")
        appendLine("    ),")
      }
      appendLine("  )")
    }
  }

  private fun sha256(
    fs: FileSystem,
    file: Path,
  ): String {
    val digest = MessageDigest.getInstance("SHA-256")
    fs.read(file) {
      val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
      while (true) {
        val read = read(buffer, 0, buffer.size)
        if (read == -1) break
        digest.update(buffer, 0, read)
      }
    }
    return digest.digest().toHex()
  }

  private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }
}
