// Generated by generateFormatsRegistry. DO NOT EDIT MANUALLY.
package io.github.optimumcode.json.schema.internal.formats

import io.github.optimumcode.json.schema.FormatValidator

/**
 * Maps JSON Schema `format` keyword values to their built-in validators.
 *
 * This file is generated by the `generateFormatsRegistry` Gradle task.
 * Do not edit it manually: add a validator object to this package and regenerate.
 */
internal object GeneratedFormatsRegistry {
  val formats: Map<String, FormatValidator> =
    mapOf(
      "date" to DateFormatValidator,
      "date-time" to DateTimeFormatValidator,
      "duration" to DurationFormatValidator,
      "email" to EmailFormatValidator,
      "hostname" to HostnameFormatValidator,
      "idn-email" to IdnEmailFormatValidator,
      "idn-hostname" to IdnHostnameFormatValidator,
      "ipv4" to IpV4FormatValidator,
      "ipv6" to IpV6FormatValidator,
      "iri" to IriFormatValidator,
      "iri-reference" to IriReferenceFormatValidator,
      "json-pointer" to JsonPointerFormatValidator,
      "regex" to RegexFormatValidator,
      "relative-json-pointer" to RelativeJsonPointerFormatValidator,
      "time" to TimeFormatValidator,
      "uri" to UriFormatValidator,
      "uri-reference" to UriReferenceFormatValidator,
      "uri-template" to UriTemplateFormatValidator,
      "uuid" to UuidFormatValidator,
    )
}