// Generated by the generateFormatRegistry Gradle task from formats/formats.json.
// Do not edit manually. Run ./gradlew :json-schema-validator:generateFormatRegistry to update.
package io.github.optimumcode.json.schema.internal.formats

import io.github.optimumcode.json.schema.FormatValidator

internal object GeneratedFormatRegistry {
  val formatNames: Set<String> =
    setOf(
      "date",
      "date-time",
      "duration",
      "email",
      "hostname",
      "idn-email",
      "idn-hostname",
      "ipv4",
      "ipv6",
      "iri",
      "iri-reference",
      "json-pointer",
      "regex",
      "relative-json-pointer",
      "time",
      "uri",
      "uri-reference",
      "uri-template",
      "uuid",
    )

  val knownFormats: Map<String, FormatValidator> =
    mapOf(
      "date" to DateFormatValidator,
      "date-time" to DateTimeFormatValidator,
      "duration" to DurationFormatValidator,
      "email" to EmailFormatValidator,
      "hostname" to HostnameFormatValidator,
      "idn-email" to IdnEmailFormatValidator,
      "idn-hostname" to IdnHostnameFormatValidator,
      "ipv4" to IpV4FormatValidator,
      "ipv6" to IpV6FormatValidator,
      "iri" to IriFormatValidator,
      "iri-reference" to IriReferenceFormatValidator,
      "json-pointer" to JsonPointerFormatValidator,
      "regex" to RegexFormatValidator,
      "relative-json-pointer" to RelativeJsonPointerFormatValidator,
      "time" to TimeFormatValidator,
      "uri" to UriFormatValidator,
      "uri-reference" to UriReferenceFormatValidator,
      "uri-template" to UriTemplateFormatValidator,
      "uuid" to UuidFormatValidator,
    )
}